name: Monitor Sísmico SGC

on:
  push:
    branches:
      - main

  schedule:
    - cron: "0,5,10,15,20,25,30,35,40,45,50,55 * * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:

      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar monitor sísmico
        run: |
          python monitor_sgc_cloud.py

      - name: Guardar cambios
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add eventos_detectados.json

          if git diff --cached --quiet; then
            echo "No hay cambios que guardar."
          else
            git commit -m "Actualizar monitor sísmico"
            git push
          fi
